Repository motioneye-project/motioneye, pull requests merged in 2022-07, with the labels that each got.

#2550 Fix failing CI tests
  l10n/traduko.sh
  motioneye/locale/ar/LC_MESSAGES/motioneye.po
  motioneye/locale/bn/LC_MESSAGES/motioneye.po
  motioneye/locale/de/LC_MESSAGES/motioneye.po
  motioneye/locale/en/LC_MESSAGES/motioneye.po
  motioneye/locale/es/LC_MESSAGES/motioneye.po
  motioneye/locale/fr/LC_MESSAGES/motioneye.po
  motioneye/locale/hi/LC_MESSAGES/motioneye.po
  motioneye/locale/it/LC_MESSAGES/motioneye.po
  motioneye/locale/ja/LC_MESSAGES/motioneye.po
  motioneye/locale/motioneye.pot
  motioneye/locale/ms/LC_MESSAGES/motioneye.po
  motioneye/locale/nb_NO/LC_MESSAGES/motioneye.po
  motioneye/locale/pa/LC_MESSAGES/motioneye.po
  motioneye/locale/pt/LC_MESSAGES/motioneye.po
  motioneye/locale/sk/LC_MESSAGES/motioneye.po
  motioneye/locale/zh/LC_MESSAGES/motioneye.po
Labels: CI/CD

#2528 replace obsolete IOLoop.instance with IOLoop.current
  motioneye/cleanup.py
  motioneye/config.py
  motioneye/controls/smbctl.py
  motioneye/handlers/action.py
  motioneye/handlers/config.py
  motioneye/handlers/picture.py
  motioneye/handlers/power.py
  motioneye/mediafiles.py
  motioneye/mjpgclient.py
  motioneye/motionctl.py
  motioneye/sendmail.py
  motioneye/sendtelegram.py
  motioneye/server.py
  motioneye/tasks.py
  motioneye/update.py
  motioneye/utils/rtsp.py
  motioneye/wsswitch.py
Labels: Python

#2547 Translations update from Hosted Weblate
  motioneye/locale/de/LC_MESSAGES/motioneye.js.po
  motioneye/locale/de/LC_MESSAGES/motioneye.mo
  motioneye/locale/de/LC_MESSAGES/motioneye.po
  motioneye/locale/ru/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ru/LC_MESSAGES/motioneye.po
Labels: i18n/l10n
