Repository motioneye-project/motioneye, pull requests merged in 2022-03, with the labels that each got.

#2309 GitHub Action to lint legacy Python
  .github/workflows/lint_legacy_python.yml
  .travis.yml
  requirements.txt
Labels: CI/CD

#1978 WIP: Motioneye Python3 Work
  motioneye/tasks.py
Labels: python update

#2316 Re-add some lost CI fixes
  .github/workflows/lint_python.yml
  motioneye/mediafiles.py
  requirements.txt
Labels: CI/CD

#2311 Travis CI last ran a year ago
  .travis.yml
Labels: CI/CD

#2321 Add pre-commit running bandit, codespell, flake8
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  setup.cfg
Labels: CI/CD

#2328 pre-commit: Enable trim trailing whitespace
  .pre-commit-config.yaml
  motioneye/Makefile
  motioneye/cleanup.py
  motioneye/controls/diskctl.py
  motioneye/controls/mmalctl.py
  motioneye/controls/powerctl.py
  motioneye/controls/smbctl.py
  motioneye/controls/tzctl.py
  motioneye/controls/v4l2ctl.py
  motioneye/controls/wifictl.py
  motioneye/extra/Dockerfile.armv7-armhf
  motioneye/extra/motioneye.conf.sample
  motioneye/meyectl.py
  motioneye/monitor.py
  motioneye/motioneye_init.py
  motioneye/prefs.py
  motioneye/remote.py
  motioneye/sendmail.py
  motioneye/sendtelegram.py
  motioneye/server.py
  motioneye/settings.py
  motioneye/shell.py
  motioneye/static/css/main.css
  motioneye/static/css/ui.css
  motioneye/static/js/frame.js
  motioneye/static/js/main.js
  motioneye/static/js/ui.js
  motioneye/tasks.py
  motioneye/template.py
  motioneye/templates/base.html
  motioneye/templates/main.html
  motioneye/traduko.sh
  motioneye/update.py
  motioneye/uploadservices.py
  motioneye/utils/rtsp.py
  motioneye/webhook.py
  motioneye/wsswitch.py
Labels: code format

#2326 GitHub Action to test our Ubuntu wiki page
  .github/workflows/ubuntu_build.yml
Labels: CI/CD

#2330 pre-commit: Enable end-of-file-fixer
  .pre-commit-config.yaml
  LICENSE
  ReadMe.md
  motioneye/controls/smbctl.py
  motioneye/extra/README.md
  motioneye/extra/motioneye.init-debian
  motioneye/extra/motioneye.svg
  motioneye/locale/motioneye.pot
  motioneye/scripts/po2json
  motioneye/scripts/relayevent.sh
  motioneye/static/css/jquery.timepicker.css
  motioneye/static/img/motioneye-icon.svg
  motioneye/static/img/no-camera.svg
  motioneye/static/img/no-preview.svg
  motioneye/static/js/jquery.timepicker.min.js
  motioneye/traduki_python.txt
  motioneye/traduko.sh
Labels: code format

#2324 GitHub Action to build using the steps in README.md
  .github/workflows/make.yml
Labels: CI/CD

#2322 Static tests are in pre-commit so focus on build, mypy, pytest, safety
  .github/workflows/lint_python.yml
  .github/workflows/test_python.yml
  requirements.txt
Labels: CI/CD

#2305 Split only two times the VCGenCMD output
  motioneye/mmalctl.py
Labels: bug

#1361 Fix error on entirely numeric camera_name
  motioneye/config.py
Labels: bug

#2275 Fix stray settings item separator tr
  motioneye/templates/main.html
Labels: enhancement, HTML/HTTP

#2345 remove buffering policy argument from open() function call
  motioneye/server.py
Labels: enhancement, python update

#2332 Do not run jobs on pull_request event on base repo
  .github/workflows/make.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test_python.yml
  .github/workflows/ubuntu_build.yml
Labels: CI/CD

#2343 pytest ignore two failing tests
  .github/workflows/test_python.yml
Labels: CI/CD

#2347 Pre-commit: Enable check-executables-have-shebangs
  .github/workflows/make.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test_python.yml
  .github/workflows/ubuntu_build.yml
  .pre-commit-config.yaml
  motioneye/scripts/po2json
Labels: CI/CD

#2334 CSS lint fixes
  motioneye/static/css/frame.css
  motioneye/static/css/main.css
  motioneye/static/css/ui.css
Labels: code format

#2348 pre-commit: Enable pyupgrade --py37-plus
  .pre-commit-config.yaml
  motioneye/__init__.py
  motioneye/cleanup.py
  motioneye/config.py
  motioneye/controls/diskctl.py
  motioneye/controls/mmalctl.py
  motioneye/controls/smbctl.py
  motioneye/controls/tzctl.py
  motioneye/controls/v4l2ctl.py
  motioneye/controls/wifictl.py
  motioneye/handlers/action.py
  motioneye/handlers/base.py
  motioneye/handlers/config.py
  motioneye/handlers/log.py
  motioneye/handlers/login.py
  motioneye/handlers/main.py
  motioneye/handlers/movie.py
  motioneye/handlers/movie_playback.py
  motioneye/handlers/picture.py
  motioneye/handlers/power.py
  motioneye/handlers/prefs.py
  motioneye/handlers/relay_event.py
  motioneye/handlers/update.py
  motioneye/mediafiles.py
  motioneye/meyectl.py
  motioneye/mjpgclient.py
  motioneye/monitor.py
  motioneye/motionctl.py
  motioneye/motioneye_init.py
  motioneye/prefs.py
  motioneye/remote.py
  motioneye/sendmail.py
  motioneye/sendtelegram.py
  motioneye/server.py
  motioneye/settings.py
  motioneye/shell.py
  motioneye/tasks.py
  motioneye/template.py
  motioneye/update.py
  motioneye/uploadservices.py
  motioneye/utils/__init__.py
  motioneye/utils/dtconv.py
  motioneye/utils/mjpeg.py
  motioneye/utils/rtmp.py
  motioneye/utils/rtsp.py
  motioneye/webhook.py
  motioneye/wsswitch.py
  tests/__init__.py
  tests/test_utils/test_mjpeg.py
Labels: CI/CD

#2349 pre-commit: Enable isort --profile black
  .pre-commit-config.yaml
  motioneye/cleanup.py
  motioneye/config.py
  motioneye/controls/diskctl.py
  motioneye/controls/powerctl.py
  motioneye/controls/smbctl.py
  motioneye/controls/tzctl.py
  motioneye/controls/v4l2ctl.py
  motioneye/controls/wifictl.py
  motioneye/handlers/action.py
  motioneye/handlers/base.py
  motioneye/handlers/config.py
  motioneye/handlers/log.py
  motioneye/handlers/login.py
  motioneye/handlers/main.py
  motioneye/handlers/movie.py
  motioneye/handlers/movie_playback.py
  motioneye/handlers/picture.py
  motioneye/handlers/power.py
  motioneye/handlers/prefs.py
  motioneye/handlers/relay_event.py
  motioneye/handlers/update.py
  motioneye/handlers/version.py
  motioneye/mediafiles.py
  motioneye/meyectl.py
  motioneye/mjpgclient.py
  motioneye/monitor.py
  motioneye/motionctl.py
  motioneye/motioneye_init.py
  motioneye/prefs.py
  motioneye/remote.py
  motioneye/sendmail.py
  motioneye/sendtelegram.py
  motioneye/server.py
  motioneye/settings.py
  motioneye/tasks.py
  motioneye/template.py
  motioneye/uploadservices.py
  motioneye/utils/__init__.py
  motioneye/utils/dtconv.py
  motioneye/utils/http.py
  motioneye/utils/mjpeg.py
  motioneye/utils/rtmp.py
  motioneye/utils/rtsp.py
  motioneye/webhook.py
  motioneye/wsswitch.py
  tests/__init__.py
  tests/test_handlers/__init__.py
  tests/test_handlers/test_base.py
  tests/test_handlers/test_login.py
  tests/test_utils/test_mjpeg.py
Labels: CI/CD

#2350 Adjust copyright note
  AUTHORS
  motioneye/templates/main.html
Labels: meta

#2344 Read camera_name as string properly
  motioneye/config.py
Labels: enhancement

#1746 Alter meta viewport to allow pinch to zoom.
  motioneye/templates/base.html
Labels: enhancement, HTML/HTTP

#2352 Remove obsolete universal_newlines parameter
  motioneye/utils/__init__.py
Labels: enhancement

#2353 Update extra files
  .github/workflows/make.yml
  .github/workflows/ubuntu_build.yml
  .gitignore
  README.md
  extra/Dockerfile
  extra/Dockerfile.armv7-armhf
  extra/README.md
  extra/docker-compose.override.yml
  extra/docker-compose.yml
  extra/motioneye-256x256.png
  extra/motioneye-64x64.png
  extra/motioneye-docker.conf
  extra/motioneye.svg
  motioneye/extra/linux_init
  motioneye/extra/motioneye.conf.sample
  motioneye/extra/motioneye.systemd
  motioneye/extra/motioneye.systemd-unit
  motioneye/extra/motioneye.sysv
  motioneye/scripts/migrateconf.sh
  setup.cfg
Labels: enhancement, meta

#2354 GitHub Action: Add shellcheck
  .github/workflows/shellcheck.yml
  .github/workflows/ubuntu_build.yml
  motioneye/extra/motioneye.sysv
  motioneye/scripts/migrateconf.sh
  motioneye/scripts/po2json
  motioneye/scripts/relayevent.sh
  motioneye/traduki_po.sh
  motioneye/traduko.sh
Labels: CI/CD

#2364 Automatic cancel old runs if a new commit is pushed
  .github/dependabot.yaml
  .github/workflows/make.yml
  .github/workflows/pre-commit.yml
  .github/workflows/shellcheck.yml
  .github/workflows/test_python.yml
  .github/workflows/ubuntu_build.yml
Labels: CI/CD

#1969 Add async to improve page load times.
  motioneye/templates/base.html
  motioneye/templates/main.html
  motioneye/templates/version.html
Labels: enhancement, HTML/HTTP

#2362 2360 unable to add rtsp or mjpeg cameras to motioneye
  motioneye/handlers/config.py
Labels: bug

#2361 Added GitHub actions docker workflow
  .github/workflows/docker.yml
  .github/workflows/make.yml
  .github/workflows/ubuntu_build.yml
  extra/Dockerfile
  extra/Dockerfile.armv7-armhf
  extra/entrypoint.sh
  motioneye/extra/linux_init
  motioneye/motioneye_init.py
  motioneye/scripts/po2json
Labels: docker, CI/CD

#2367 Fix Docker workflow condition
  .github/workflows/docker.yml
Labels: docker, CI/CD

#2356 Update README.rst
  README.rst
Labels: meta

#2337 Add info about cifs-utils for SMB shares
  motioneye/extra/motioneye.conf.sample
Labels: meta

#2211 Change `onResponse` argument to avoid dependency on error pages
  motioneye/static/js/main.js
Labels: feature, JavaScript

#2370 Update external assets
  motioneye/static/css/jquery.timepicker.css
  motioneye/static/css/jquery.timepicker.min.css
  motioneye/static/js/css-browser-selector.js
  motioneye/static/js/css-browser-selector.min.js
  motioneye/static/js/gettext.min.js
  motioneye/static/js/jquery.min.js
  motioneye/static/js/jquery.mousewheel.js
  motioneye/static/js/jquery.mousewheel.min.js
  motioneye/static/js/jquery.timepicker.min.js
  motioneye/templates/base.html
Labels: CSS, JavaScript, dependencies

#2371 Fix RPi vcgencmd parsing
  motioneye/controls/mmalctl.py
Labels: bug

#2110 Create timelapse movies using specified codec instead of forcing avi
  motioneye/handlers/picture.py
  motioneye/mediafiles.py
Labels: enhancement, feature

#2351 pre-commit: Enable black --skip-string-normalization
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  motioneye/cleanup.py
  motioneye/config.py
  motioneye/controls/diskctl.py
  motioneye/controls/powerctl.py
  motioneye/controls/smbctl.py
  motioneye/controls/tzctl.py
  motioneye/controls/v4l2ctl.py
  motioneye/controls/wifictl.py
  motioneye/handlers/action.py
  motioneye/handlers/base.py
  motioneye/handlers/config.py
  motioneye/handlers/main.py
  motioneye/handlers/movie.py
  motioneye/handlers/movie_playback.py
  motioneye/handlers/picture.py
  motioneye/handlers/relay_event.py
  motioneye/handlers/update.py
  motioneye/handlers/version.py
  motioneye/mediafiles.py
  motioneye/meyectl.py
  motioneye/mjpgclient.py
  motioneye/monitor.py
  motioneye/motionctl.py
  motioneye/prefs.py
  motioneye/remote.py
  motioneye/sendmail.py
  motioneye/sendtelegram.py
  motioneye/server.py
  motioneye/tasks.py
  motioneye/template.py
  motioneye/update.py
  motioneye/uploadservices.py
  motioneye/utils/__init__.py
  motioneye/utils/dtconv.py
  motioneye/utils/http.py
  motioneye/utils/mjpeg.py
  motioneye/utils/rtsp.py
  motioneye/wsswitch.py
  tests/__init__.py
  tests/test_handlers/test_login.py
  tests/test_utils/test_http.py
  tests/test_utils/test_mjpeg.py
  tests/test_utils/test_rtmp.py
Labels: CI/CD, code format

#2369 Update and align install commands
  .github/workflows/make.yml
  .github/workflows/test_python.yml
  .github/workflows/ubuntu_build.yml
  README.md
  extra/Dockerfile
  motioneye/extra/linux_init
Labels: enhancement, CI/CD

#2374 Minor arithemtic enhancements
  motioneye/utils/dtconv.py
Labels: code format

#1914 add webhook for motion event ends
  motioneye/config.py
  motioneye/static/js/main.js
  motioneye/templates/main.html
Labels: feature

#2377 Minor README format fix
  README.md
Labels: meta

#2386 Fix Docker container by copying entrypoint in place
  extra/Dockerfile
Labels: bug, docker
