Repository motioneye-project/motioneye, pull requests merged in 2022-04, with the labels that each got.

#2403 Update pre-commit and remove numpy dependency
  .pre-commit-config.yaml
  motioneye/utils/__init__.py
  setup.cfg
Labels: CI/CD, dependencies

#2380 Minor code enhancements
  motioneye/controls/v4l2ctl.py
  motioneye/handlers/base.py
Labels: code format, Python

#2388 Docker - Fix uid/gid replacement as motion user does not exist at that time.
  docker/Dockerfile
Labels: bug, docker

#2376 Fix S3 and add generic S3 compatible server support
  motioneye/config.py
  motioneye/static/js/main.js
  motioneye/templates/main.html
  motioneye/uploadservices.py
Labels: bug, feature

#2412 Remove now unused armhf build dependencies
  docker/Dockerfile
Labels: docker

#2410 Fix missing fdisk package - issue 2409
  docker/Dockerfile
Labels: bug, docker

#1968 Add support for fullscreenchange event to exit full screen mode
  Makefile
  motioneye/locale/ar/LC_MESSAGES/motioneye.js.po
  motioneye/locale/bn/LC_MESSAGES/motioneye.js.po
  motioneye/locale/de/LC_MESSAGES/motioneye.js.po
  motioneye/locale/en/LC_MESSAGES/motioneye.js.po
  motioneye/locale/es/LC_MESSAGES/motioneye.js.po
  motioneye/locale/fr/LC_MESSAGES/motioneye.js.po
  motioneye/locale/hi/LC_MESSAGES/motioneye.js.po
  motioneye/locale/it/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ja/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ms/LC_MESSAGES/motioneye.js.po
  motioneye/locale/pa/LC_MESSAGES/motioneye.js.po
  motioneye/locale/pt/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ru/LC_MESSAGES/motioneye.js.po
  motioneye/locale/zh/LC_MESSAGES/motioneye.js.po
  motioneye/static/css/main.css
  motioneye/static/img/camera-top-buttons.svg
  motioneye/static/js/main.js
  motioneye/static/js/motioneye.ar.json
  motioneye/static/js/motioneye.bn.json
  motioneye/static/js/motioneye.de.json
  motioneye/static/js/motioneye.en.json
  motioneye/static/js/motioneye.es.json
  motioneye/static/js/motioneye.fr.json
  motioneye/static/js/motioneye.hi.json
  motioneye/static/js/motioneye.it.json
  motioneye/static/js/motioneye.ja.json
  motioneye/static/js/motioneye.ms.json
  motioneye/static/js/motioneye.pa.json
  motioneye/static/js/motioneye.pt.json
  motioneye/static/js/motioneye.ru.json
  motioneye/static/js/motioneye.zh.json
Labels: feature

#2420 Send telegram bug fix
  motioneye/config.py
  motioneye/extra/motioneye.conf.sample
  motioneye/sendtelegram.py
Labels: bug

#2416 Fix and enhance request handling
  motioneye/uploadservices.py
Labels: bug, enhancement, code format, Python

#2424 Fix for invalid motion and privacy ui json values (Issue #2423)
  motioneye/utils/__init__.py
Labels: bug, Python

#2426 Fixes for video and image view now (Issue #2421)
  motioneye/static/js/css-browser-selector.min.js
  motioneye/static/js/frame.js
  motioneye/static/js/main.js
  motioneye/static/js/ui.js
  motioneye/static/js/version.js
Labels: bug, JavaScript

#2432 send HTTP/1.0 to motion webcontrol instead of HTTP/1.1
  motioneye/mjpgclient.py
Labels: enhancement, Python

#2437 Fix timelapse from pictures generation
  motioneye/mediafiles.py
Labels: bug, enhancement, python update, Python

#2445 Fix for overlapping play and timelapse buttons (Issue #2431)
  motioneye/static/css/main.css
  motioneye/static/img/camera-top-buttons.svg
Labels: bug

#2446 Camera settings button toggles configuration open/close. Fixes #2435
  motioneye/static/js/main.js
Labels: feature
