Repository motioneye-project/motioneye, pull requests merged in 2022-11, with the labels that each got.

#2633 Fix 'No cameras configured' due to changed 'videodevice' string
  motioneye/utils/__init__.py
Labels: bug

#2642 Fix flake8 which moved from GitLab to GitHub
  .pre-commit-config.yaml
Labels: CI/CD

#2639 Translations update from Hosted Weblate
  motioneye/locale/es/LC_MESSAGES/motioneye.js.po
  motioneye/locale/es/LC_MESSAGES/motioneye.mo
  motioneye/locale/es/LC_MESSAGES/motioneye.po
Labels: i18n/l10n

#2641 Remove faulty %-escaping in f-string
  motioneye/config.py
Labels: bug, Python

#2644 Remove faulty classmethod annotation
  motioneye/uploadservices.py
Labels: bug, Python

#2647 Translations update from Hosted Weblate
  motioneye/locale/de/LC_MESSAGES/motioneye.js.po
  motioneye/locale/de/LC_MESSAGES/motioneye.mo
  motioneye/locale/de/LC_MESSAGES/motioneye.po
  motioneye/locale/nl/LC_MESSAGES/motioneye.js.po
  motioneye/locale/nl/LC_MESSAGES/motioneye.mo
  motioneye/locale/nl/LC_MESSAGES/motioneye.po
Labels: i18n/l10n

#2651 [CI/CD] pre-commit autoupdate
  .github/workflows/pre-commit-autoupdate.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
Labels: CI/CD

#2654 Add scheduled workflow to default branch
  .github/workflows/lint_legacy_python.yml
  .github/workflows/pre-commit-autoupdate.yml
Labels: CI/CD, meta

#2655 [CI/CD] Fix pre-commit autoupdate workflow
  .github/workflows/pre-commit-autoupdate.yml
Labels: bug, CI/CD
