Repository motioneye-project/motioneye, pull requests merged in 2022-06, with the labels that each got.

#2515 Translations update from Hosted Weblate
  motioneye/locale/pt/LC_MESSAGES/motioneye.js.po
  motioneye/locale/pt/LC_MESSAGES/motioneye.mo
  motioneye/locale/pt/LC_MESSAGES/motioneye.po
Labels: i18n/l10n

#2486 Fixes for video stream authentications
  motioneye/config.py
  motioneye/mjpgclient.py
  motioneye/utils/__init__.py
  motioneye/utils/mjpeg.py
Labels: bug, Python

#2517 Upgrade workflows to use Ubuntu Jammy runners
  .github/dependabot.yaml
  .github/workflows/docker.yml
  .github/workflows/make.yml
  .github/workflows/pre-commit.yml
  .github/workflows/shellcheck.yml
  .github/workflows/test_python.yml
  .github/workflows/ubuntu_build.yml
Labels: CI/CD

#2519 #2518: Webhooks - fix "data" parameter type
  motioneye/webhook.py
Labels: bug, python update
