Repository motioneye-project/motioneye, pull requests merged in 2022-10, with the labels that each got.

#2608 Disable daily dev upload
  .github/workflows/pypi_release.yml
Labels: CI/CD

#2594 Allow arbitrary values for all percentage settings
  motioneye/templates/main.html
Labels: enhancement

#2462 Add support for motion v4.4
  motioneye/config.py
  motioneye/extra/linux_init
  motioneye/motionctl.py
Labels: enhancement, help wanted, motion
