Repository motioneye-project/motioneye, pull requests merged in 2022-05, with the labels that each got.

#1743 add file upload support for webdav
  motioneye/templates/main.html
  motioneye/uploadservices.py
Labels: feature

#2457 pre-commit autoupdate
  .pre-commit-config.yaml
Labels: CI/CD

#2460 Fix for page load causes 403 request (#2363)
  motioneye/static/js/main.js
Labels: bug

#2452 Start motionEye service after filesystem targets
  motioneye/extra/motioneye.systemd
Labels: bug

#2464 Fixed remote motioneye camera config bug. (#2449)
  motioneye/handlers/config.py
  motioneye/remote.py
Labels: bug, python update

#2456 POST data should be bytes.
  motioneye/uploadservices.py
Labels: bug, python update, Python

#2478 use BytesIO instead of StringIO for binary data
  motioneye/uploadservices.py
Labels: bug, python update, Python

#2482 Update Docker Compose config to pull from GitHub registry
  docker/docker-compose.override.yml
  docker/docker-compose.yml
Labels: docker

#2483 Python3: PIL requires image as bytes object
  motioneye/mediafiles.py
Labels: bug, python update, Python

#2490 Translations update from Hosted Weblate
  motioneye/locale/es/LC_MESSAGES/motioneye.js.po
  motioneye/locale/es/LC_MESSAGES/motioneye.mo
  motioneye/locale/es/LC_MESSAGES/motioneye.po
Labels: i18n/l10n

#2496 2491 v4l controls localization
  Makefile
  l10n/v4l2.js
  motioneye/locale/ar/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ar/LC_MESSAGES/motioneye.mo
  motioneye/locale/bn/LC_MESSAGES/motioneye.js.po
  motioneye/locale/bn/LC_MESSAGES/motioneye.mo
  motioneye/locale/de/LC_MESSAGES/motioneye.js.po
  motioneye/locale/de/LC_MESSAGES/motioneye.mo
  motioneye/locale/en/LC_MESSAGES/motioneye.js.po
  motioneye/locale/en/LC_MESSAGES/motioneye.mo
  motioneye/locale/es/LC_MESSAGES/motioneye.js.po
  motioneye/locale/fr/LC_MESSAGES/motioneye.js.po
  motioneye/locale/fr/LC_MESSAGES/motioneye.mo
  motioneye/locale/hi/LC_MESSAGES/motioneye.js.po
  motioneye/locale/hi/LC_MESSAGES/motioneye.mo
  motioneye/locale/it/LC_MESSAGES/motioneye.js.po
  motioneye/locale/it/LC_MESSAGES/motioneye.mo
  motioneye/locale/ja/LC_MESSAGES/motioneye.js.po
  motioneye/locale/motioneye.js.pot
  motioneye/locale/motioneye.pot
  motioneye/locale/ms/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ms/LC_MESSAGES/motioneye.mo
  motioneye/locale/nb_NO/LC_MESSAGES/motioneye.js.po
  motioneye/locale/nb_NO/LC_MESSAGES/motioneye.mo
  motioneye/locale/nb_NO/LC_MESSAGES/motioneye.po
  motioneye/locale/pa/LC_MESSAGES/motioneye.js.po
  motioneye/locale/pa/LC_MESSAGES/motioneye.mo
  motioneye/locale/pt/LC_MESSAGES/motioneye.js.po
  motioneye/locale/pt/LC_MESSAGES/motioneye.mo
  motioneye/locale/ru/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ru/LC_MESSAGES/motioneye.mo
  motioneye/locale/sk/LC_MESSAGES/motioneye.js.po
  motioneye/locale/sk/LC_MESSAGES/motioneye.mo
  motioneye/locale/sk/LC_MESSAGES/motioneye.po
  motioneye/locale/zh/LC_MESSAGES/motioneye.js.po
  motioneye/static/js/main.js
  motioneye/static/js/motioneye.ar.json
  motioneye/static/js/motioneye.bn.json
  motioneye/static/js/motioneye.de.json
  motioneye/static/js/motioneye.en.json
  motioneye/static/js/motioneye.es.json
  motioneye/static/js/motioneye.fr.json
  motioneye/static/js/motioneye.hi.json
  motioneye/static/js/motioneye.it.json
  motioneye/static/js/motioneye.ja.json
  motioneye/static/js/motioneye.ms.json
  motioneye/static/js/motioneye.nb_NO.json
  motioneye/static/js/motioneye.pa.json
  motioneye/static/js/motioneye.pt.json
  motioneye/static/js/motioneye.ru.json
  motioneye/static/js/motioneye.sk.json
  motioneye/static/js/motioneye.zh.json
Labels: i18n/l10n

#2502 Create pypi_daily_build.yml
  .github/workflows/pypi_daily_build.yml
Labels: CI/CD

#2505 Clarify that piwheels should be used on 32-bit ARM only
  README.md
Labels: documentation
