Repository motioneye-project/motioneye, pull requests merged in 2023-03, with the labels that each got.

#2711 CI | Fix dist-upgrade on Jammy tests
  .github/workflows/test_python.yml
  .github/workflows/ubuntu_build.yml
  motioneye/locale/motioneye.js.pot
  motioneye/locale/motioneye.pot
Labels: CI/CD

#2705 use media_files.result()
  motioneye/sendmail.py
Labels: bug

#2717 Fix camera-overlay div sometimes being clickable (but invisible) on creation
  motioneye/static/js/main.js
Labels: bug, JavaScript

#2722 Fix locale scripts
  Makefile
  l10n/po2json
  l10n/traduki_po.sh
  l10n/traduko.sh
  motioneye/locale/ar/LC_MESSAGES/motioneye.js.po
  motioneye/locale/bn/LC_MESSAGES/motioneye.js.po
  motioneye/locale/cs/LC_MESSAGES/motioneye.js.po
  motioneye/locale/de/LC_MESSAGES/motioneye.js.po
  motioneye/locale/el/LC_MESSAGES/motioneye.js.po
  motioneye/locale/en/LC_MESSAGES/motioneye.js.po
  motioneye/locale/es/LC_MESSAGES/motioneye.js.po
  motioneye/locale/es/LC_MESSAGES/motioneye.mo
  motioneye/locale/es/LC_MESSAGES/motioneye.po
  motioneye/locale/fr/LC_MESSAGES/motioneye.js.po
  motioneye/locale/hi/LC_MESSAGES/motioneye.js.po
  motioneye/locale/hu/LC_MESSAGES/motioneye.js.po
  motioneye/locale/hu/LC_MESSAGES/motioneye.mo
  motioneye/locale/hu/LC_MESSAGES/motioneye.po
  motioneye/locale/it/LC_MESSAGES/motioneye.js.po
  motioneye/locale/it/LC_MESSAGES/motioneye.mo
  motioneye/locale/it/LC_MESSAGES/motioneye.po
  motioneye/locale/ja/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ko/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ko/LC_MESSAGES/motioneye.mo
  motioneye/locale/motioneye.js.pot
  motioneye/locale/motioneye.pot
  motioneye/locale/ms/LC_MESSAGES/motioneye.js.po
  motioneye/locale/nb_NO/LC_MESSAGES/motioneye.js.po
  motioneye/locale/nl/LC_MESSAGES/motioneye.js.po
  motioneye/locale/pa/LC_MESSAGES/motioneye.js.po
  motioneye/locale/pl/LC_MESSAGES/motioneye.js.po
  motioneye/locale/pl/LC_MESSAGES/motioneye.mo
  motioneye/locale/pl/LC_MESSAGES/motioneye.po
  motioneye/locale/pt/LC_MESSAGES/motioneye.js.po
  motioneye/locale/pt/LC_MESSAGES/motioneye.mo
  motioneye/locale/pt/LC_MESSAGES/motioneye.po
  motioneye/locale/ro/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ru/LC_MESSAGES/motioneye.js.po
  motioneye/locale/sk/LC_MESSAGES/motioneye.js.po
  motioneye/locale/sk/LC_MESSAGES/motioneye.mo
  motioneye/locale/sv/LC_MESSAGES/motioneye.js.po
  motioneye/locale/sv/LC_MESSAGES/motioneye.mo
  motioneye/locale/sv/LC_MESSAGES/motioneye.po
  motioneye/locale/uk/LC_MESSAGES/motioneye.js.po
  motioneye/locale/zh/LC_MESSAGES/motioneye.js.po
  motioneye/static/js/motioneye.el.json
  motioneye/static/js/motioneye.es.json
  motioneye/static/js/motioneye.hu.json
  motioneye/static/js/motioneye.it.json
  motioneye/static/js/motioneye.ko.json
  motioneye/static/js/motioneye.nb_NO.json
  motioneye/static/js/motioneye.nl.json
  motioneye/static/js/motioneye.pl.json
  motioneye/static/js/motioneye.pt.json
  motioneye/static/js/motioneye.ro.json
  motioneye/static/js/motioneye.ru.json
  motioneye/static/js/motioneye.sv.json
  motioneye/static/js/motioneye.zh.json
Labels: CI/CD, i18n/l10n

#2720 README: Update translation status
  README.md
  motioneye/locale/motioneye.js.pot
  motioneye/locale/motioneye.pot
Labels: meta, i18n/l10n

#2724 Translations update from Hosted Weblate
  motioneye/locale/pt/LC_MESSAGES/motioneye.js.po
  motioneye/locale/pt/LC_MESSAGES/motioneye.mo
  motioneye/locale/pt/LC_MESSAGES/motioneye.po
Labels: i18n/l10n

#2736 CI | Disable Google Translator usage for now
  Makefile
  motioneye/locale/motioneye.js.pot
  motioneye/locale/motioneye.pot
  motioneye/locale/pt/LC_MESSAGES/motioneye.mo
Labels: CI/CD, i18n/l10n

#2738 CI | Update only locale templates and frontend JSON files
  .github/workflows/update_locales.yml
  motioneye/locale/motioneye.js.pot
  motioneye/locale/motioneye.pot
  motioneye/static/js/motioneye.ru.json
  motioneye/static/js/motioneye.zh.json
Labels: CI/CD, i18n/l10n
