Repository motioneye-project/motioneye, pull requests merged in 2024-05, with the labels that each got.

#2980 motioneye_init: stop and disable conflicting motion.service
  .github/workflows/test_python.yml
  motioneye/extra/linux_init
  motioneye/locale/motioneye.js.pot
  motioneye/locale/motioneye.pot
Labels: bug

#2983 enhance motion startup logging and update "safety" workflow
  .github/workflows/python_safety.yml
  motioneye/mediafiles.py
  motioneye/motionctl.py
Labels: enhancement, CI/CD, Python

#2903 Increase amount of action buttons
  .gitignore
  motioneye/static/css/main.css
  motioneye/static/img/camera-action-button-alarm-off.svg
  motioneye/static/img/camera-action-button-alarm-on.svg
  motioneye/static/img/camera-action-button-down.svg
  motioneye/static/img/camera-action-button-left.svg
  motioneye/static/img/camera-action-button-light-off.svg
  motioneye/static/img/camera-action-button-light-on.svg
  motioneye/static/img/camera-action-button-lock.svg
  motioneye/static/img/camera-action-button-preset.svg
  motioneye/static/img/camera-action-button-record-start.svg
  motioneye/static/img/camera-action-button-record-stop.svg
  motioneye/static/img/camera-action-button-right.svg
  motioneye/static/img/camera-action-button-snapshot.svg
  motioneye/static/img/camera-action-button-unlock.svg
  motioneye/static/img/camera-action-button-up.svg
  motioneye/static/img/camera-action-button-zoom-in.svg
  motioneye/static/img/camera-action-button-zoom-out.svg
  motioneye/static/img/camera-action-buttons.svg
  motioneye/static/js/main.js
Labels: enhancement, CSS, JavaScript

#2993 ci: switch to or add Ubuntu Noble runners
  .github/workflows/docker.yml
  .github/workflows/pre-commit-autoupdate.yml
  .github/workflows/pre-commit.yml
  .github/workflows/pypi_release.yml
  .github/workflows/python_safety.yml
  .github/workflows/shellcheck.yml
  .github/workflows/test_python.yml
  .github/workflows/ubuntu_build.yml
  .github/workflows/update_locales.yml
Labels: CI/CD

#2994 Bump to 0.43.1b2
  motioneye/__init__.py
Labels: meta
