Repository motioneye-project/motioneye, pull requests merged in 2024-06, with the labels that each got.

#3000 ci: ignore another newly failing Python safety CVE
  .github/workflows/docker.yml
  .github/workflows/python_safety.yml
Labels: CI/CD

#3004 Merge main => dev
  .github/workflows/docker.yml
  .github/workflows/python_safety.yml
Labels: meta

#2999 Translations update from Hosted Weblate
  motioneye/locale/hu/LC_MESSAGES/motioneye.js.po
  motioneye/locale/hu/LC_MESSAGES/motioneye.mo
  motioneye/locale/hu/LC_MESSAGES/motioneye.po
  motioneye/locale/motioneye.js.pot
  motioneye/locale/motioneye.pot
  motioneye/static/js/motioneye.hu.json
Labels: i18n/l10n

#3014 Translations update from Hosted Weblate
  motioneye/locale/ar/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ar/LC_MESSAGES/motioneye.po
  motioneye/locale/bn/LC_MESSAGES/motioneye.js.po
  motioneye/locale/bn/LC_MESSAGES/motioneye.po
  motioneye/locale/ca/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ca/LC_MESSAGES/motioneye.po
  motioneye/locale/cs/LC_MESSAGES/motioneye.js.po
  motioneye/locale/cs/LC_MESSAGES/motioneye.po
  motioneye/locale/de/LC_MESSAGES/motioneye.js.po
  motioneye/locale/de/LC_MESSAGES/motioneye.po
  motioneye/locale/el/LC_MESSAGES/motioneye.js.po
  motioneye/locale/el/LC_MESSAGES/motioneye.po
  motioneye/locale/en/LC_MESSAGES/motioneye.js.po
  motioneye/locale/en/LC_MESSAGES/motioneye.po
  motioneye/locale/es/LC_MESSAGES/motioneye.js.po
  motioneye/locale/es/LC_MESSAGES/motioneye.po
  motioneye/locale/fi/LC_MESSAGES/motioneye.js.po
  motioneye/locale/fi/LC_MESSAGES/motioneye.po
  motioneye/locale/fr/LC_MESSAGES/motioneye.js.po
  motioneye/locale/fr/LC_MESSAGES/motioneye.po
  motioneye/locale/hi/LC_MESSAGES/motioneye.js.po
  motioneye/locale/hi/LC_MESSAGES/motioneye.po
  motioneye/locale/hu/LC_MESSAGES/motioneye.js.po
  motioneye/locale/hu/LC_MESSAGES/motioneye.po
  motioneye/locale/it/LC_MESSAGES/motioneye.js.po
  motioneye/locale/it/LC_MESSAGES/motioneye.po
  motioneye/locale/ja/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ja/LC_MESSAGES/motioneye.po
  motioneye/locale/ko/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ko/LC_MESSAGES/motioneye.po
  motioneye/locale/ms/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ms/LC_MESSAGES/motioneye.po
  motioneye/locale/nb_NO/LC_MESSAGES/motioneye.js.po
  motioneye/locale/nb_NO/LC_MESSAGES/motioneye.po
  motioneye/locale/nl/LC_MESSAGES/motioneye.js.po
  motioneye/locale/nl/LC_MESSAGES/motioneye.po
  motioneye/locale/pa/LC_MESSAGES/motioneye.js.po
  motioneye/locale/pa/LC_MESSAGES/motioneye.po
  motioneye/locale/pl/LC_MESSAGES/motioneye.js.po
  motioneye/locale/pl/LC_MESSAGES/motioneye.po
  motioneye/locale/pt/LC_MESSAGES/motioneye.js.po
  motioneye/locale/pt/LC_MESSAGES/motioneye.po
  motioneye/locale/ro/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ro/LC_MESSAGES/motioneye.po
  motioneye/locale/ru/LC_MESSAGES/motioneye.js.po
  motioneye/locale/ru/LC_MESSAGES/motioneye.po
  motioneye/locale/sk/LC_MESSAGES/motioneye.js.po
  motioneye/locale/sk/LC_MESSAGES/motioneye.po
  motioneye/locale/sv/LC_MESSAGES/motioneye.js.po
  motioneye/locale/sv/LC_MESSAGES/motioneye.po
  motioneye/locale/tr/LC_MESSAGES/motioneye.js.po
  motioneye/locale/tr/LC_MESSAGES/motioneye.po
  motioneye/locale/uk/LC_MESSAGES/motioneye.js.po
  motioneye/locale/uk/LC_MESSAGES/motioneye.po
  motioneye/locale/zh/LC_MESSAGES/motioneye.js.po
  motioneye/locale/zh/LC_MESSAGES/motioneye.po
Labels: i18n/l10n

#3020 Make snapshot/streaming/embed (URLs) pop-ups work on all translations
  motioneye/static/js/main.js
Labels: bug, JavaScript
